""""2024-12-13 01:09:46.435007"

Revision ID: 0ac8d8080c05
Revises: 5e5b14fad4f5
Create Date: 2024-12-13 01:09:48.667744

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ac8d8080c05'
down_revision: Union[str, None] = '5e5b14fad4f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
