""""2024-12-13 01:32:08.907663"

Revision ID: 1ed1695a9b02
Revises: b95017d61997
Create Date: 2024-12-13 01:32:11.008396

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ed1695a9b02'
down_revision: Union[str, None] = 'b95017d61997'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
