""""2024-12-13 00:56:31.467186"

Revision ID: 208535a9dfbe
Revises: 3a8e7a0daf26
Create Date: 2024-12-13 00:56:33.557918

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '208535a9dfbe'
down_revision: Union[str, None] = '3a8e7a0daf26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
