""""2024-12-13 01:29:36.389954"

Revision ID: 2bfa636c098d
Revises: 96b3fb563c87
Create Date: 2024-12-13 01:29:38.445152

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2bfa636c098d'
down_revision: Union[str, None] = '96b3fb563c87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
