""""2024-12-13 00:50:32.843500"

Revision ID: 2c1521ee335a
Revises: cba9f824ba22
Create Date: 2024-12-13 00:50:34.950828

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c1521ee335a'
down_revision: Union[str, None] = 'cba9f824ba22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
