"""Intial

Revision ID: 2e1a8f54b96b
Revises: 812d51f9e3b8
Create Date: 2024-12-12 01:07:14.268557

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e1a8f54b96b'
down_revision: Union[str, None] = '812d51f9e3b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('subject_name', sa.String(), nullable=False))
    op.drop_column('events', 'subject_id')
    op.create_unique_constraint(None, 'users', ['student_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.add_column('events', sa.Column('subject_id', sa.BIGINT(), autoincrement=False, nullable=False))
    op.drop_column('events', 'subject_name')
    # ### end Alembic commands ###
