""""2024-12-13 01:12:38.546534"

Revision ID: 36d824078dc2
Revises: 01ad737b4670
Create Date: 2024-12-13 01:12:40.684954

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36d824078dc2'
down_revision: Union[str, None] = '01ad737b4670'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
