""""2024-12-13 00:55:31.788358"

Revision ID: 3a8e7a0daf26
Revises: b67ea0994c50
Create Date: 2024-12-13 00:55:33.874434

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a8e7a0daf26'
down_revision: Union[str, None] = 'b67ea0994c50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('settings', 'teacher_in_schedule')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('teacher_in_schedule', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
