""""2024-12-13 00:49:51.016908"

Revision ID: 3bcb01c31624
Revises: a00931b0cf07
Create Date: 2024-12-13 00:49:53.117589

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3bcb01c31624'
down_revision: Union[str, None] = 'a00931b0cf07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
