""""2024-12-13 01:37:26.583854"

Revision ID: 4ca13d1261bd
Revises: 1ed1695a9b02
Create Date: 2024-12-13 01:37:28.737820

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ca13d1261bd'
down_revision: Union[str, None] = '1ed1695a9b02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
