"""Intial

Revision ID: 51c90fcf5188
Revises: 296b01bd99b8
Create Date: 2024-12-12 00:29:05.118310

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51c90fcf5188'
down_revision: Union[str, None] = '296b01bd99b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('student_id', sa.BigInteger(), nullable=False))
    op.add_column('events', sa.Column('subject_id', sa.BigInteger(), nullable=False))
    op.add_column('events', sa.Column('teacher_id', sa.BigInteger(), nullable=False))
    op.create_foreign_key(None, 'events', 'users', ['student_id'], ['student_id'], ondelete='CASCADE')
    op.drop_column('events', 'subject_name')
    op.drop_column('events', 'student_profile_id')
    op.drop_column('events', 'description')
    op.drop_column('events', 'teacher_name')
    op.create_unique_constraint(None, 'users', ['student_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.add_column('events', sa.Column('teacher_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('events', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('events', sa.Column('student_profile_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('events', sa.Column('subject_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.drop_column('events', 'teacher_id')
    op.drop_column('events', 'subject_id')
    op.drop_column('events', 'student_id')
    # ### end Alembic commands ###
