""""2024-12-13 01:16:20.074697"

Revision ID: 60cc02ea010e
Revises: da434328e60f
Create Date: 2024-12-13 01:16:22.296498

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60cc02ea010e'
down_revision: Union[str, None] = 'da434328e60f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
