""""2024-12-13 01:07:53.904841"

Revision ID: 6eec69d11226
Revises: d0c5b2315bd4
Create Date: 2024-12-13 01:07:56.184754

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6eec69d11226'
down_revision: Union[str, None] = 'd0c5b2315bd4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
