""""2024-12-13 01:13:16.579064"

Revision ID: 7202803b7e9c
Revises: 36d824078dc2
Create Date: 2024-12-13 01:13:18.639607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7202803b7e9c'
down_revision: Union[str, None] = '36d824078dc2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
