""""2024-12-13 01:01:56.399835"

Revision ID: 8b0882a6e8a1
Revises: 208535a9dfbe
Create Date: 2024-12-13 01:01:58.542616

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b0882a6e8a1'
down_revision: Union[str, None] = '208535a9dfbe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
