""""2024-12-13 01:29:01.266130"

Revision ID: 96b3fb563c87
Revises: a02ea2d9b049
Create Date: 2024-12-13 01:29:03.379859

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96b3fb563c87'
down_revision: Union[str, None] = 'a02ea2d9b049'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
