""""2024-12-13 00:46:03.238726"

Revision ID: 99d982595e27
Revises: d983ed3a48d0
Create Date: 2024-12-13 00:46:05.308839

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99d982595e27'
down_revision: Union[str, None] = 'd983ed3a48d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
