""""2024-12-13 01:27:39.035228"

Revision ID: a02ea2d9b049
Revises: e464ffff6acb
Create Date: 2024-12-13 01:27:41.226957

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a02ea2d9b049'
down_revision: Union[str, None] = 'e464ffff6acb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
