""""2024-12-13 01:30:50.072498"

Revision ID: a9d686b334eb
Revises: 2bfa636c098d
Create Date: 2024-12-13 01:30:52.256917

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9d686b334eb'
down_revision: Union[str, None] = '2bfa636c098d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
