""""2024-12-13 00:54:02.584530"

Revision ID: b67ea0994c50
Revises: 2c1521ee335a
Create Date: 2024-12-13 00:54:04.792886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b67ea0994c50'
down_revision: Union[str, None] = '2c1521ee335a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
