""""2024-12-13 01:31:01.566055"

Revision ID: be564a2e0def
Revises: a9d686b334eb
Create Date: 2024-12-13 01:31:03.744923

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be564a2e0def'
down_revision: Union[str, None] = 'a9d686b334eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
