""""2024-12-13 01:04:20.841923"

Revision ID: cea38a93228c
Revises: 8b0882a6e8a1
Create Date: 2024-12-13 01:04:23.021207

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cea38a93228c'
down_revision: Union[str, None] = '8b0882a6e8a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
