""""2024-12-13 01:07:28.212103"

Revision ID: d0c5b2315bd4
Revises: a6391a61238f
Create Date: 2024-12-13 01:07:30.353275

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0c5b2315bd4'
down_revision: Union[str, None] = 'a6391a61238f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
