""""2024-12-13 00:42:48.462267"

Revision ID: d983ed3a48d0
Revises: 2e1a8f54b96b
Create Date: 2024-12-13 00:42:50.491403

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd983ed3a48d0'
down_revision: Union[str, None] = '2e1a8f54b96b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('teacher_in_schedule', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('settings', 'teacher_in_schedule')
    # ### end Alembic commands ###
