""""2024-12-13 01:14:48.920976"

Revision ID: da434328e60f
Revises: 7202803b7e9c
Create Date: 2024-12-13 01:14:51.037238

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da434328e60f'
down_revision: Union[str, None] = '7202803b7e9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
