""""2024-12-13 01:24:36.796703"

Revision ID: e464ffff6acb
Revises: 60cc02ea010e
Create Date: 2024-12-13 01:24:38.980593

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e464ffff6acb'
down_revision: Union[str, None] = '60cc02ea010e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
