from app.keyboards.user.auth import *
from app.keyboards.user.different import *
from app.keyboards.user.homeworks import *
from app.keyboards.user.marks import *
from app.keyboards.user.menu import *
from app.keyboards.user.premium import *
from app.keyboards.user.results import *
from app.keyboards.user.schedule import *
from app.keyboards.user.settings import *
from app.keyboards.user.utils import *
